# GitHub Actions CI for a Rust project
# Triggers on push to main and on pull requests targeting main.
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry and target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Setup Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy rustfmt || true

      - name: Build
        run: cargo build --all --verbose

      - name: Run tests
        run: cargo test --all --verbose

      - name: Run Clippy
        run: cargo clippy --all -- -D warnings

      - name: Check formatting
        run: cargo fmt -- --check
